output_dir: ./models/train_p=2_Llama1B
model_path: ./models/Llama3.2-1B

# Model Arguments
model:
  _component_: torchtune.models.llama3_2.lora_llama3_2_1b
  lora_attn_modules: ['q_proj', 'v_proj', 'output_proj']
  apply_lora_to_mlp: True
  lora_rank: 64 
  lora_alpha: 128  
  lora_dropout: 0.0

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ${model_path}/original/tokenizer.model
  max_seq_len: null

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ${model_path}
  checkpoint_files: [
     model.safetensors
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA3_2
resume_from_checkpoint: False
save_adapter_weights_only: False

dataset:
  - _component_: torchtune.datasets.chat_dataset
    conversation_column: conversations
    conversation_style: openai
    packed: False
    source: json
    data_files: data/instruct_skillmix.json
    role: main
    phase: 0
    epochs: 8

  - _component_: torchtune.datasets.chat_dataset
    conversation_column: conversations
    conversation_style: openai
    packed: False
    source: json
    data_files: data/safety_finetuning_dataset.json
    role: main
    phase: 1
    epochs: 5

  - _component_: torchtune.datasets.chat_dataset
    conversation_column: conversations
    conversation_style: openai
    packed: False
    source: json
    data_files: data/TOFU_full_chat.json
    role: main
    phase: 2
    epochs: 2

  - _component_: torchtune.datasets.chat_dataset
    conversation_column: conversations
    conversation_style: openai
    packed: False
    source: json
    data_files: data/gsm8k-gpt4o-train.json
    role: main
    phase: 3
    epochs: 2

########################################################
seed: 42
batch_size: 2
gradient_accumulation_steps: 32
save_every_n_epochs: 4
max_new_tokens: 1024

eval_data_path: None

optimizer:
  _component_: torch.optim.AdamW
  fused: True
  weight_decay: 0.00
  lr: 5e-5

# lr_scheduler:
#   _component_: torchtune.training.lr_schedulers.get_wsd
#   num_warmup_steps: 2
#   drop_iter: 2

lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 10

loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
########################################################

shuffle: True
  
max_steps_per_epoch: null
clip_grad_norm: null
compile: False

log_every_n_steps: 12

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.WandBLogger
  project: impossibility-of-retrain-equivalence
  log_dir: ./wandb

# Environment
device: cuda
dtype: fp32
enable_activation_checkpointing: False  # True reduces memory
enable_activation_offloading: False  # True reduces memory